# Generated by Django 4.2.5 on 2023-12-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_purchaseorder_po_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
