# Generated by Django 4.2.5 on 2023-12-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_purchaseorder_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchaseorder",
                to="app.vendor",
            ),
        ),
    ]
